name = "onebooknav"
main = "workers/index.js"
compatibility_date = "2024-01-01"

# Environment variables
[vars]
SITE_TITLE = "OneBookNav"
DEFAULT_ADMIN_USERNAME = "admin"
DEFAULT_ADMIN_EMAIL = "admin@example.com"
AUTO_CREATE_ADMIN = "true"

# D1 Database binding
# REQUIRED: Create database first: wrangler d1 create onebooknav
# Then replace "YOUR_DATABASE_ID_HERE" with the actual database ID
# Example: database_id = "01234567-89ab-cdef-0123-456789abcdef"
[[d1_databases]]
binding = "DB"
database_name = "onebooknav"
database_id = "YOUR_DATABASE_ID_HERE"