# OneBookNav Cloudflare Workers Configuration

name = "onebooknav"
main = "index.js"
compatibility_date = "2024-01-01"

# Environment variables
[vars]
SITE_TITLE = "OneBookNav"
SITE_URL = "https://onebooknav.your-domain.workers.dev"
# Admin account will be created automatically on first run
DEFAULT_ADMIN_USERNAME = "admin"
DEFAULT_ADMIN_EMAIL = "admin@example.com"
AUTO_CREATE_ADMIN = "true"

# D1 Database binding
# REQUIRED: Create database first: wrangler d1 create onebooknav
# Then replace "YOUR_DATABASE_ID_HERE" with the actual database ID
# Example: database_id = "01234567-89ab-cdef-0123-456789abcdef"
[[d1_databases]]
binding = "DB"
database_name = "onebooknav"
database_id = "YOUR_DATABASE_ID_HERE"

# R2 Storage binding for static assets (optional)
# Uncomment if you plan to use R2 for static assets
# [[r2_buckets]]
# binding = "STORAGE"
# bucket_name = "onebooknav-assets"

# KV for caching (optional)
# Uncomment if you plan to use KV for caching
# [[kv_namespaces]]
# binding = "CACHE"
# id = "your-kv-namespace-id"

# Secrets (set via wrangler secret)
# IMPORTANT: Set these secrets before deployment:
# wrangler secret put JWT_SECRET
# wrangler secret put DEFAULT_ADMIN_PASSWORD

# Custom domains (comment out if using workers.dev subdomain)
# [routes]
# pattern = "onebooknav.your-domain.com/*"
# zone_name = "your-domain.com"

# Workers 不需要构建步骤，代码直接部署

# Development configuration
[env.development]
vars = {
  SITE_TITLE = "OneBookNav Dev",
  DEFAULT_ADMIN_USERNAME = "admin",
  DEFAULT_ADMIN_EMAIL = "admin@example.com",
  AUTO_CREATE_ADMIN = "true"
}

[[env.development.d1_databases]]
binding = "DB"
database_name = "onebooknav-dev"
database_id = "YOUR_DEV_DATABASE_ID_HERE"

# Production configuration
[env.production]
vars = {
  SITE_TITLE = "OneBookNav",
  DEFAULT_ADMIN_USERNAME = "admin",
  DEFAULT_ADMIN_EMAIL = "admin@example.com",
  AUTO_CREATE_ADMIN = "true"
}

[[env.production.d1_databases]]
binding = "DB"
database_name = "onebooknav-prod"
database_id = "YOUR_PROD_DATABASE_ID_HERE"